### PR TITLE
[MWRAPPER-58] add -L to curl command

### PR DESCRIPTION
**Pull request by gzm55**
curl should follow redirection to download the wrapper jar

### CODE REVIEW

**Review by slawekjaranowski — CHANGES_REQUESTED** [review]
Please follow in PR title and git commit format:  `[ISSUE-1111]` - square brackets can be important for our tools 😄 

Maybe something like for wget and curl:
```
f [ -n "$MVNW_USERNAME" ] && [ -n "$MVNW_PASSWORD" ]; then
 AUTH="USER + NAME options"
else
 AUTH=""
fi

wget ... $AUTH ... || rm -f "$wrapperJarPath"
```

it will be more readable then 

```
...
fi || rm ...
```

**Comment by gzm55** [comment]
@slawekjaranowski title is fixed

the password may contain some special characters for shell, so `AUTH=...` options may require some eval tricks in posix shell to correctly invoke the `curl` or `wget`

**Comment by slawekjaranowski** [comment]
but what do you think about:

```
...
fi

[ $? -eq 0 ] || rm ...
```

simply not look good for me

```
fi || rm ..
```

**Comment by gzm55** [comment]
> but what do you think about:
> 
> ```
> ...
> fi
> 
> [ $? -eq 0 ] || rm ...
> ```
> 
> simply not look good for me
> 
> ```
> fi || rm ..
> ```

new commit fix is.

**Review by slawekjaranowski — APPROVED** [review]

**Comment by hboutemy** [comment]
merged in https://github.com/apache/maven-wrapper/commit/313654df5a8cd06f12ce619eff9ff26d8d019497

thank you

**Comment by jira-importer** [comment]
Resolve #252

**Comment by jira-importer** [comment]
Resolve #252

**Pull request closed without merging**
