### PR TITLE
[MWRAPPER-103] Workaround: demote check to Warning

### PR DESCRIPTION
**Pull request by cstamas**
For start, instead to die off, let's demote the failure to warning level.

---

https://issues.apache.org/jira/browse/MWRAPPER-103

### CODE REVIEW

**Comment by cstamas** [comment]
@gsmet eyes please. Disclaimer: I am not Win guy, so if you can bring on someone to verify, please do so.

**Comment by cstamas** [comment]
@jorsol eyes please

**Comment by jorsol** [comment]
The issue affects the `wrapperSha256Sum` from `mvnw`, not `only-mvnw`, actually the only-mvnw does not validate the `wrapperSha256Sum` since it doesn't download the jar.

In the end, this is not the fix for the issue reported, the trouble is that `only-mvnw` does different things than `mvnw`, so it seems that using `only-mvnw` works and `mvnw` don't.

**Comment by cstamas** [comment]
Oh, got it now. Ok, am closing this one out then, as I missed the topic.

**Comment by jorsol** [comment]
Since the default is now `only-mvnw`, maybe the current workaround is to simply remove the lines from:

https://github.com/apache/maven-wrapper/blob/c9a3e67e5295c41b4a9bc4fd4babe81d20e7e18f/maven-wrapper-distribution/src/resources/mvnw.cmd#L156-L172

Or comment the  `if ERRORLEVEL 1 goto error`.

**Comment by cstamas** [comment]
Yup, that is my problem as well: "not sure" :smile:

**Comment by cstamas** [comment]
Next attempt: https://github.com/apache/maven-wrapper/pull/132

**Comment by jira-importer** [comment]
Resolve #292

**Comment by jira-importer** [comment]
Resolve #292

**Pull request closed without merging**
