### PR TITLE
[MWRAPPER-33] Use java 8 in maven-wrapper

### PR DESCRIPTION
**Pull request by amitmisra-ww**
Updated the `javaVersion` to `8` in the parent module. 

Steps followed: 

1. Changed the `pom.xml` to a java `8` 
2. Ran `mvn -Prun-its verify` successfully
3. Generated the `maven-wrapper.jar` and `maven-wrapper-plugin.jar`
4. Created a simple project using Spring Initializr 
5. Updated `./mvn/wrapper/maven-wrapper.properties` file to use the `plugin.jar` to point to `$HOME/.m2/repository/org/apache/maven/plugins/maven-wrapper-plugin/3.2.0-SNAPSHOT/maven-wrapper-plugin-3.2.0-SNAPSHOT.jar`
6. Replaced `maven-wrapper.jar` with the one generated in Step 3 above
7. Build the project and ran it successfully using like so -
```
$ ./mvnw clean install 
$ ./mvnw spring-boot:run
```

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MWRAPPER) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MWRAPPER-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MWRAPPER-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
Please also check project for existing other place connected with `1.7`, 
like `https.protocols` in `maven-wrapper-plugin/pom.xml`

**Comment by amitmisra-ww** [comment]
@slawekjaranowski please let me know if there is anything else required for this PR to be accepted. Thanks.

**Review by bmarwell — APPROVED** [review]

**Comment by bmarwell** [comment]
This is blocking https://issues.apache.org/jira/browse/MWRAPPER-77. If there are no objections within the next week, I will merge it to move forward.

**Comment by slawekjaranowski** [comment]
@bmarwell - done 😄

**Comment by slawekjaranowski** [comment]
@amitmisra-ww thanks.

**Comment by jira-importer** [comment]
Resolve #210

**Comment by jira-importer** [comment]
Resolve #210

**Pull request merged**
