### PR TITLE
[MWRAPPER-108] Emit clear error message when download fails on U*IX

### PR DESCRIPTION
**Pull request by cstamas**
Script silently just failed. Reused changes from dead PR https://github.com/apache/maven-wrapper/pull/98 w/ help of @michael-o :+1:  Thanks both!

---

https://issues.apache.org/jira/browse/MWRAPPER-108

### CODE REVIEW

**Review by michael-o — APPROVED** [review]

**Comment by cstamas** [comment]
@michael-o ouch, the IT failed on Windows... so same should be done there as well.... :sos:

**Comment by michael-o** [comment]
> @michael-o ouch, the IT failed on Windows... so same should be done there as well.... 🆘

Let guess: Those images have the tools installed...

**Comment by michael-o** [comment]
WTF:
```
icm : Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At line:1 char:125
+ ... 'mvnw.cmd'; icm -ScriptBlock ([Scriptblock]::Create((Get-Content -Raw ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Command], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.InvokeCommandCommand
 
VERBOSE: Couldn't find MAVEN_HOME, downloading and installing it ...
VERBOSE: Downloading from: http://localhost:62622/org/apache/maven/apache-maven/0.0.0/apache-maven-0.0.0-bin.zip
VERBOSE: Downloading to: C:\Users\runneradmin\AppData\Local\Temp\tmp6E64.tmp.dir/apache-maven-0.0.0-bin.zip
Cannot start maven from wrapper  
```

**Comment by cstamas** [comment]
Seems this issue affected only non-windows scripts, as on Windows is not wget/curl downloading, and that something does emit error (got 404). But on nonWindows OSes the message was unclear (like "missing XXX" instead "could not download")

**Comment by jira-importer** [comment]
Resolve #308

**Pull request merged**
