### PR TITLE
[MWRAPPER-80] support maven-mvnd

### PR DESCRIPTION
**Pull request by gzm55**
Try to integrate maven-mvnd as a maven distribution. The `mvnd` use a native executable as entry or a new entry class in generic version to communicate with the background daemon. So we can only execute the `mvnd` by the wrapper script with `only-script` distribution type. Now `only-mvnw` (for *nix OS) and `only-mvnw.cmd` (for windows) work fine without sha256 checksum verification.

- manual select platform: distributionUrl=https://downloads.apache.org/maven/mvnd/0.8.2/maven-mvnd-0.8.2-darwin-amd64.zip
- auto select platform: distributionUrl=https://downloads.apache.org/maven/mvnd/0.8.2/maven-mvnd-0.8.2-bin.zip

In the auto mode, the script selects a proper platform via the result of "uname -a", or fallback to the pure java version for unknown platform. For `distributionSha256Sum`, we also need new pattern to support multiple checksums, such as `distributionSha256Sum=darwin-aarch64:111,linux-amd64:222`

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MWRAPPER) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[MWRAPPER-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MWRAPPER-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [X] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [X] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Review by nicoloboschi — APPROVED** [review]

**Comment by nicoloboschi** [comment]
This is a great feature!
@bmarwell @amitmisra-ww @slawekjaranowski PTAL

**Comment by slawekjaranowski** [comment]
please also add IT test - to see how it works

What with additional task per OS, like for macOs `xattr -r -d ...`?

https://github.com/apache/maven-mvnd#install-manually

**Comment by gzm55** [comment]
> What with additional task per OS, like for macOs `xattr -r -d ...`?
> 
> https://github.com/apache/maven-mvnd#install-manually

The "com.apple.quarantine" extended attribute is set when the zip/tgz files are downloaded by the browsers, and not set when downloaded by curl/wget/java. This is tested on macos since 10.15. And the original maven distribution installed by wrapper also relies on this behavior. So the `xattr -r -d ...` step is not required by the wrapper for both original maven and mvnd.

**Comment by bmarwell** [comment]
> and not set when downloaded by curl/wget/java

Yes this is true, for whatever reason.

**Comment by gzm55** [comment]
> please also add IT test - to see how it works

IT test is added. The test case success on linux and macos, but failed on windows since not implemented in `mvnw.cmd`.

**Comment by gzm55** [comment]
@slawekjaranowski @bmarwell `mvnw` and `mvnw.cmd` both pass the IT test.

**Comment by gzm55** [comment]
@slawekjaranowski could you give some suggestions or review for this pr?

**Comment by slawekjaranowski** [comment]
If we support only `only-script` WrapperMojo should detect it and set proper `distributionType` in other case it will not works ... I'm right?

**Comment by gzm55** [comment]
> If we support only `only-script` WrapperMojo should detect it and set proper `distributionType` in other case it will not works ... I'm right?

yes, a fast-fail check is added in `execute()` of the mojo

**Comment by jira-importer** [comment]
Resolve #270

**Comment by jira-importer** [comment]
Resolve #270

**Pull request merged**
