### PR TITLE
[MWRAPPER-134] Add wrapperVersion to maven-wrapper.properties

### PR DESCRIPTION
**Pull request by cstamas**
That contains the current version of the deployed Maven Wrapper

---

https://issues.apache.org/jira/browse/MWRAPPER-134

### CODE REVIEW

**Comment by cstamas** [comment]
@breun ping

**Review by slawekjaranowski — APPROVED** [review]

**Comment by breun** [comment]
@cstamas Thanks, I think this should work! 👍

**Comment by jira-importer** [comment]
Resolve #249

**Comment by jira-importer** [comment]
Resolve #249

**Pull request merged**
