### PR TITLE
[MWRAPPER-47] - Use name wrapperUrl consistently in Maven Wrapper files/scripts

### PR DESCRIPTION
**Pull request by jimisola**
Replaced jarUrl with wrapperUrl in mvnw

My first maven contribution in 15 years or so. Please advise if I missed out on something.

### CODE REVIEW

**Comment by hboutemy** [comment]
nice
while at it, we could rename also DOWNLOAD_URL to WRAPPER_URL in mvnw.cmd, WDYT?
and eventually better align choices in mvnw.cmd vs mvnw

**Comment by jimisola** [comment]
I agree. I've renamed DOWNLOAD_URL to WRAPPER_URL in mvnw.cmd. Although, it was a simple find-replace it has not been tested since I don't use Windows. 

Not sure what choices you are referring to (command line option?), but that will be clearer with another Jira issue :)

**Comment by hboutemy** [comment]
> Not sure what choices you are referring to (command line option?), but that will be clearer with another Jira issue :)

I have no concrete case in mind, just the idea that there may be other cases of such differences between mvnw.cmd and mvnw that could be avoided to have a better consistency

**Comment by hboutemy** [comment]
thank you

**Comment by jira-importer** [comment]
Resolve #238

**Pull request merged**
